/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sparqltest_SparqlParser */

#ifndef _Included_sparqltest_SparqlParser
#define _Included_sparqltest_SparqlParser
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     sparqltest_SparqlParser
 * Method:    parse_query
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sparqltest_SparqlParser_parse_1query
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
